name: system
version: 1.0
main: dev.system.system
api-version: 1.20
commands:
  fly:
    description: Toggle fly mode
    usage: /fly
    permission: system.fly
  nightvision:
    description: Toggle night vision effect
    usage: /nightvision
    permission: system.nightvision
  gm:
    description: Change your gamemode
    usage: /gm <0|1|2|3>
    permission: system.gamemode
  heal:
    description: Heal yourself to full health
    usage: /heal
    permission: system.heal
  feed:
    description: Feed yourself
    usage: /feed
    permission: system.feed
  god:
    description: Toggle god mode (invulnerability)
    usage: /god
    permission: system.god
  permsgive:
    description: Give a permission to a player
    usage: /permsgive <player> <permission>
    permission: system.perms.give
  help:
    description: Shows a list of commands
    usage: /help
  clearchat:
    description: Clears the chat for all players
    permission: system.clearchat
  announce:
    description: Broadcasts an important announcement to the server
    usage: /announce <message>
    permission: system.announce
  tp:
    description: Teleport to another player
    usage: /tp <player>
    permission: system.tp
  tphere:
    description: Teleport a player to you
    usage: /tphere <player>
    permission: system.tphere